In [1]:
import numpy as np 
A = np.array([[3.5,3.4,6.2,6.3],[3.4,7.87,4.67,10],[6.2,4.67,11.87,10],[6.3,10,10,14.7]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues: ")
print(eigenvalues)

print("\nEigenvectors: ")
print(eigenvectors)           

Eigenvalues: 
[3.19343650e+01 5.86108481e+00 2.14341152e-02 1.23116075e-01]

Eigenvectors: 
[[ 0.31332966  0.22982975 -0.69623644  0.60353759]
 [ 0.42357542 -0.59916745 -0.44909081 -0.50980357]
 [ 0.52754512  0.71021085  0.0727161  -0.46044442]
 [ 0.66641169 -0.28944292  0.55523385  0.40476367]]


In [14]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

data=pd.read_csv("Advertising.csv")
data.head()



,Unnamed: 0,TV,Radio,Newspaper,Sales
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9


In [3]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [7]:
pca=PCA(n_components=2)
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)

In [8]:
pca_df_train=pd.DataFrame(x_train_pca,columns=["PCA1","PCA2"])
pca_df_test=pd.DataFrame(x_test_pca,columns=["PCA1","PCA2"])

print("All PCA1 values(train):")
print(pca_df_train["PCA1"])

print("All PCA1 values(test):")
print(pca_df_test["PCA1"])


All PCA1 values(train):
0     -0.811320
1     -1.920261
2      0.581606
3     -0.493166
4     -1.429190
         ...   
155   -0.700753
156    1.526337
157    1.545547
158   -1.423840
159   -0.722954
Name: PCA1, Length: 160, dtype: float64
All PCA1 values(test):
0     1.184135
1     2.388902
2     1.232587
3     0.632101
4     0.158717
5     1.116364
6     1.074764
7    -1.397175
8    -1.773304
9     0.376910
10   -0.781391
11   -1.342440
12    0.679778
13   -0.407173
14   -1.538328
15   -0.917478
16    0.709915
17   -0.763727
18   -0.007339
19   -0.154950
20    1.825308
21    3.796885
22   -0.241958
23    2.149132
24   -1.448839
25   -1.072944
26    1.164291
27   -0.848700
28   -0.837093
29   -1.079874
30   -0.601276
31   -0.105111
32    2.470448
33    2.890778
34   -0.316195
35   -0.256009
36    0.024721
37    1.164673
38   -1.588294
39   -1.234514
Name: PCA1, dtype: float64


In [9]:
model=LinearRegression()
model.fit(x_train_pca,y_train)


LinearRegression()

In [10]:
y_pred=model.predict(x_test_pca)

In [13]:
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print("Mean Squared Error :",mse)
print("R2 Score:",r2)

Mean Squared Error : 8.474443447283297
R2 Score: 0.7315120859048789
